### ISSUE TITLE
I couldn't find the Sonic Pi server executable :(

### ISSUE THREAD

**Issue by dsolito** [lpil/sonic-pi-tool#32]
hello,
sonic-pi-tool start-server
gives me an error :
I couldn't find the Sonic Pi server executable :(

sonic-pi 3.2.2 App is in Applications folder.
I am on mac os 10.14.4

what can I do ?

thanks

**Comment by lpil** [comment]
Hi there! Sonic Pi recently made some changes in how the server accepts code (it now uses a random code and the server start script has moved). This has broken sonic-pi-tool but hopefully we'll be able to fix it in future.

For now consider using an older version of Sonic Pi or using the build in Sonic Pi GUI editor.

**Comment by technicalpickles** [comment]
Ran into this too, and foudn the sonic-pi-server.rb at `/Applications/Sonic Pi.app/Contents/Resources/server/ruby/bin/sonic-pi-server.rb`

You can manually run it like `ruby /Applications/Sonic\ Pi.app/Contents/Resources/server/ruby/bin/sonic-pi-server.rb`, and then `sonic-pi-tool check` should work.

**Comment by dsolito** [comment]
Thanks, but when I do that, I have a connection refused

Connection refused - send(2)
["/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:621:in `block in <main>'"]

**Comment by lpil** [comment]
This is because Sonic Pi has changed how to connect to the server. There is no fix at present.

**Comment by dsolito** [comment]
thank you @technicalpickles and @lpil !
David

**Comment by lpil** [comment]
I'm going to re-open this as it still a problem

**Comment by dsolito** [comment]
Ok, I was not able to comment without closing it. Sorry.

**Comment by lpil** [comment]
No worries! Thank you for the bug report!

**Comment by adrianlyjak** [comment]
Looking to automate a pi with sonic-pi-tool. Just a heads up, if anyone else is looking for a workaround,  currently [`v3.3.1`](https://github.com/sonic-pi-net/sonic-pi/releases/tag/v3.3.1) is the latest version of sonic-pi with the [`sonic-pi-server.rb`](https://github.com/sonic-pi-net/sonic-pi/blob/v3.3.1/app/server/ruby/bin/sonic-pi-server.rb) file. It was dropped in the subsequent v4.0.0 release

**Comment by rsmath** [comment]
where does sonic-pi-tool look for the server file?
