### ISSUE TITLE
Errors on starting server, but the server still works

### ISSUE THREAD

**Issue by NightMachinery** [lpil/sonic-pi-tool#35]
```
❯ sonic-pi-tool start-server                                                                                              
/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ffi-1.11.3/lib/ffi/platform.rb:61: warning: already initialized constant FFI::Platform::CPU
Sonic Pi server booting...
This is version 3.2.0 running on Ruby 2.6.4.
The time is 2020-08-10 19:31:12 +0430
Using primary protocol: udp
Detecting port numbers...
Listen port: 4557
  - OK
Scsynth port: 4556
  - OK
Scsynth send port: 4556
  - OK
OSC cues port: 4560
  - OK
Erlang port: 4561
  - OK
OSC MIDI out port: 4563
  - OK
OSC MIDI in port: 4564
  - OK
Websocket port: 4562
  - OK
Opening UDP Server to listen to GUI on port: 4557
Starting Server Runtime
Booting server...


Booting Sonic Pi
----------------

Boot - Booting on OS X
Boot - Checkout audio rates on OSX:
Boot - Unable to detect audio rates. Disabling input
Boot - Booting with no audio inputs
Boot - Starting the SuperCollider server...
Boot - /Applications/Sonic Pi.app/Contents/Resources/app/server/native/scsynth -u 4556 -a 1024 -m 131072 -D 0 -R 0 -l 1 -i 0 -o 16 -U /Applications/Sonic Pi.app/Contents/Resources/app/server/native/supercollider/plugins/ -b 4096 -B 127.0.0.1
Ignoring charlock_holmes-0.7.7 because its extensions are not built. Try: gem pristine charlock_holmes --version 0.7.7
Ignoring escape_utils-1.2.1 because its extensions are not built. Try: gem pristine escape_utils --version 1.2.1
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring github-linguist-7.9.0 because its extensions are not built. Try: gem pristine github-linguist --version 7.9.0
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring rugged-1.0.1 because its extensions are not built. Try: gem pristine rugged --version 1.0.1
Started [23800] [-] /Applications/Sonic Pi.app/Contents/Resources/app/server/native/scsynth -u 4556 -a 1024 -m 131072 -D 0 -R 0 -l 1 -i 0 -o 16 -U /Applications/Sonic Pi.app/Contents/Resources/app/server/native/supercollider/plugins/ -b 4096 -B 127.0.0.1 [-] /var/folders/5v/g3zxt_7d64g3sd_56bzpqbvh0000gn/T/sonic-pi-pids/23800
Boot - SuperCollider booted successfully.
Boot - Connecting to the SuperCollider server...
Boot - Sending /status to server: 127.0.0.1:4556
Boot - Receiving ack from scsynth
Boot - Server connection established
Studio - Initialised SuperCollider Audio Server v3.11.0
Studio - Resetting server
Studio - Studio - clearing scsynth
Studio - Studio - allocating audio bus
Studio - Studio - Create Base Synth Groups
Studio - Starting mixer
Studio - Starting scope
exec "/Applications/Sonic Pi.app/Contents/Resources/app/server/native/ruby/bin/ruby" "/Applications/Sonic Pi.app/Contents/Resources/app/server/native/erlang/erl" -noshell -pz "/Applications/Sonic Pi.app/Contents/Resources/app/server/erlang" -s pi_server start 4561 4560 4557
Ignoring charlock_holmes-0.7.7 because its extensions are not built. Try: gem pristine charlock_holmes --version 0.7.7
Ignoring escape_utils-1.2.1 because its extensions are not built. Try: gem pristine escape_utils --version 1.2.1
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring github-linguist-7.9.0 because its extensions are not built. Try: gem pristine github-linguist --version 7.9.0
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring rugged-1.0.1 because its extensions are not built. Try: gem pristine rugged --version 1.0.1
Started [23805] [-] /Applications/Sonic Pi.app/Contents/Resources/app/server/native/erlang/dist/bin/beam.smp -- -root /Applications/Sonic Pi.app/Contents/Resources/app/server/native/erlang/dist -progname erl -- -home /Users/evar -- -noshell -pz /Applications/Sonic Pi.app/Contents/Resources/app/server/erlang -s pi_server start 4561 4560 4557 -- [-] /var/folders/5v/g3zxt_7d64g3sd_56bzpqbvh0000gn/T/sonic-pi-pids/23805
Studio - Spawning o2m with:
    exec '/Applications/Sonic Pi.app/Contents/Resources/app/server/native/osmid/o2m' -L -b -i 4563 -O 4564 -m 6
Ignoring charlock_holmes-0.7.7 because its extensions are not built. Try: gem pristine charlock_holmes --version 0.7.7
Ignoring escape_utils-1.2.1 because its extensions are not built. Try: gem pristine escape_utils --version 1.2.1
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring github-linguist-7.9.0 because its extensions are not built. Try: gem pristine github-linguist --version 7.9.0
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring rugged-1.0.1 because its extensions are not built. Try: gem pristine rugged --version 1.0.1
Started [23808] [-] /Applications/Sonic Pi.app/Contents/Resources/app/server/native/osmid/o2m -L -b -i 4563 -O 4564 -m 6 [-] /var/folders/5v/g3zxt_7d64g3sd_56bzpqbvh0000gn/T/sonic-pi-pids/23808
Studio - Spawning m2o with:
    exec '/Applications/Sonic Pi.app/Contents/Resources/app/server/native/osmid/m2o' -t /midi:\$n:\$i:\$c/\$m -b -o 4564 -m 6 'Sonic Pi'
Ignoring charlock_holmes-0.7.7 because its extensions are not built. Try: gem pristine charlock_holmes --version 0.7.7
Ignoring escape_utils-1.2.1 because its extensions are not built. Try: gem pristine escape_utils --version 1.2.1
Ignoring ffi-1.9.25 because its extensions are not built. Try: gem pristine ffi --version 1.9.25
Ignoring github-linguist-7.9.0 because its extensions are not built. Try: gem pristine github-linguist --version 7.9.0
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring rugged-1.0.1 because its extensions are not built. Try: gem pristine rugged --version 1.0.1
Started [23810] [-] /Applications/Sonic Pi.app/Contents/Resources/app/server/native/osmid/m2o -t /midi:$n:$i:$c/$m -b -o 4564 -m 6 Sonic Pi [-] /var/folders/5v/g3zxt_7d64g3sd_56bzpqbvh0000gn/T/sonic-pi-pids/23810
Studio - Initialised MIDI subsystems
This is Sonic Pi v3.2.2 running on osx with ruby api 2.6.0.
Sonic Pi Server successfully booted.
Exception!
Connection refused - send(2)
["/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:621:in `block in <main>'"]
Exception!
Connection refused - send(2)
["/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:621:in `block in <main>'"]
Exception!
Connection refused - send(2)
["/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:621:in `block in <main>'"]
Exception!
Connection refused - send(2)
["/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/osc/udp_client.rb:31:in `send'", "/Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:621:in `block in <main>'"]
```

The server still works for a simple command like `sonic-pi-tool eval 'play 60'`. Should I just ignore these errors?

**Comment by NightMachinery** [comment]
Seems like this is a duplicate of https://github.com/lpil/sonic-pi-tool/issues/32 , so I am going to close this.
